service: DIOLiveServerlessProject
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  #Definindo a Região onde será instanciado
  region: sa-east-1
  #Criando Roles de perimissão de realizar requisições no banco de dados
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:scan
          Resource:
            - arn:aws:dynamodb:sa-east-1:339587003374:table/ItemTableNew

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  insertItem:
    handler: src/insertItem.handler
    events:
      - httpApi:
          path: /adicionar
          method: post
  fetchItems:
    handler: src/fetchitems.handler
    events:
      - httpApi:
          path: /listar
          method: get
  fetchItem:
    handler: src/fetchItem.handler
    events:
      - httpApi:
          path: /listar/{id}
          method: get
  updateItem:
    handler: src/updateItem.handler
    events:
      - httpApi:
          path: /atualizar/{id}
          method: put
  
#Criando a tabela de banco no DYNAMODB
resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
